# Changes here will be overwritten by Copier
_commit: '3917165'
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: '2025'
documentation: true
email: nick@koston.org
full_name: J. Nick Koston
github_username: kohlerlibs
has_cli: false
initial_commit: false
is_django_package: false
open_source_license: MIT
open_with_editor: false
package_name: aiokem
project_name: aiokem
project_short_description: Async API for Kohler Energy Management
project_slug: aiokem
run_uv_sync: false
setup_github: false
setup_pre_commit: false

